### ISSUE TITLE
Wrong Coding Style

### ISSUE THREAD

**Issue by recons** [ReactiveX/RxPHP#173]
http://www.php-fig.org/psr/psr-2/#methods
`_subscribe` are u srs?

**Comment by davidwdan** [comment]
We ended up leaving  it`_subscribe` because it's not part of the public API, we didn't have any great alternative names, and we're not big fans of bike shedding.

I'm going to close this issue.  If there is a specific issue you experience directly related to the naming of `_subscribe`, please feel free to reopen it with examples.
